services:
  db:
    build: ./database
    restart: always
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - edhub_postgres_storage:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:12345678@db:5432/edhub
    depends_on:
      - db

  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - db
      - backend

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend

volumes:
  edhub_postgres_storage:
