services:
  db:
    build: ./database
    restart: always
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - edhub_postgres_storage:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - edhub-network

  backend:
    build: ./backend
    restart: always
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://postgres:12345678@db:5432/edhub
    depends_on:
      - db
    networks:
      - edhub-network

volumes:
  edhub_postgres_storage:

networks:
  edhub-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16