name: Code style tests

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  check_todo:
    runs-on: ubuntu-latest
    name: Check for TODO comments in code
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for TODO comments
        run: |
          todo_files=$(grep -r "TODO" --include=\*.{py,js,jsx} . || true)
          if [ -z "$todo_files" ]; then
            echo "No TODOs found"
          else
            echo "TODOs found"
            echo "$todo_files"
            exit 1
          fi
