name: Frontend Smoke Test

on:
  push:
  pull_request:
    branches: [ main, dev ]

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    name: Frontend Smoke Test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build frontend
        run: docker build -t edhub-frontend -f frontend/Dockerfile ./frontend

      - name: Run frontend container
        run: docker run -d -p 3000:3000 --name frontend edhub-frontend

      - name: Wait for frontend
        run: sleep 10

      - name: Check frontend response
        run: curl -f http://localhost:3000 || (docker logs frontend && exit 1)

      - name: Stop container
        if: always()
        run: docker stop frontend && docker rm frontend
