name: Application Launch tests

on:
  push:
  pull_request:
    branches: [ main, dev ]

jobs:
  docker-compose-dev:
    runs-on: ubuntu-latest
    name: Test docker compose (staging)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker compose up
        run: |
          docker compose up -d --build
      
      - name: Wait for system_db to be ready
        run: |
          echo "Waiting for system_db to be ready..."
          for i in {1..30}; do
            if docker compose exec system_db pg_isready -U postgres; then
              echo "system_db is ready!"
              exit 0
            fi
            echo "Waiting for system_db... ($i/30)"
            sleep 2
          done
          echo "system_db failed to start"
          exit 1

      - name: Wait for filestorage_db to be ready  
        run: |
          echo "Waiting for filestorage_db to be ready..."
          for i in {1..30}; do
            if docker compose exec filestorage_db pg_isready -U postgres; then
              echo "filestorage_db is ready!"
              exit 0
            fi
            echo "Waiting for filestorage_db... ($i/30)"
            sleep 2
          done
          echo "filestorage_db failed to start"
          exit 1

      - name: Check backend health
        run: |
          curl -f http://localhost/api/openapi.json || \
          curl -f http://localhost/api/docs || \
          curl -f http://localhost/api/health || \
          (echo "Backend is not responsive" && docker compose logs backend && exit 1)

      - name: Check frontend health
        run: |
          curl -f http://localhost/ || \
          (echo "Frontend is not responsive" && docker compose logs frontend nginx && exit 1)

      - name: Docker compose down
        if: always()
        run: |
          docker compose down -v
