name: Application Launch tests

on:
  push:
  pull_request:
    branches: [ main, dev ]

jobs:
  docker-compose-dev:
    runs-on: ubuntu-latest
    name: Test docker compose (staging)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validate docker-compose configuration
        run: |
          docker compose config
          if [ $? -ne 0 ]; then
            echo "docker-compose.yml is invalid"
            exit 1
          fi
          echo "docker-compose.yml is valid"

      - name: Build and start docker compose
        run: |
          docker compose up -d --build
          if [ $? -ne 0 ]; then
            echo "Docker compose build or start failed"
            docker compose logs
            exit 1
          fi
          echo "Docker compose build and start succeeded"

      - name: Docker compose down
        if: always()
        run: |
          docker compose down -v
  
  docker-compose-prod:
    runs-on: ubuntu-latest
    name: Test docker compose (production)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validate docker-compose configuration
        run: |
          docker compose -f docker-compose.prod.yml config
          if [ $? -ne 0 ]; then
            echo "docker-compose.yml is invalid"
            exit 1
          fi
          echo "docker-compose.yml is valid"

      - name: Build and start docker compose
        run: |
          docker compose -f docker-compose.prod.yml up -d --build
          if [ $? -ne 0 ]; then
            echo "Docker compose build or start failed"
            docker compose -f docker-compose.prod.yml logs
            exit 1
          fi
          echo "Docker compose build and start succeeded"

      - name: Docker compose down
        if: always()
        run: |
          docker compose -f docker-compose.prod.yml down -v
