name: Application Launch tests

on:
  push:
  pull_request:
    branches: [ main, dev ]

jobs:
  docker-compose-dev:
    runs-on: ubuntu-latest
    name: Testing docker compose (staging)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker compose up
        run: |
          docker compose up -d --build

      - name: Wait for database to be ready
        run: |
          until docker compose exec system_db pg_isready -U postgres; do
            sleep 1
          done
          until docker compose exec filestorage_db pg_isready -U postgres; do
            sleep 1
          done
          sleep 3

      - name: Wait for services to be ready
        run: |
          for i in {1..30}; do
            if curl -f http://localhost/api/health; then
              break
            fi
            sleep 2
          done
          if docker compose ps | grep -q "exited"; then
            echo "Some containers have exited!"
            docker compose logs
            exit 1
          fi

      - name: Check backend health
        run: |
          curl -f http://localhost/api/openapi.json || \
          curl -f http://localhost/api/docs || \
          curl -f http://localhost/api/health || \
          (echo "Backend is not responsive" && docker compose logs backend && exit 1)

      - name: Check frontend health
        run: |
          curl -f http://localhost/ || \
          (echo "Frontend is not responsive" && docker compose logs frontend nginx && exit 1)

      - name: Docker compose down
        if: always()
        run: |
          docker compose down -v